b3scale
helsinki-systems/bbb4nix pull request #108
Opened 2021-04-06 22:31 UTC by ajs124

2021-04-07 06:29 UTC, dasJ commented
![image](https://user-images.githubusercontent.com/4971975/113820749-69660f80-977b-11eb-985e-7cfa8b31b2e4.png)

2021-04-07 07:24 UTC, dasJ requested changes

2021-04-07 07:24 UTC, dasJ commented on packages/b3scale/default.nix
> +      hidden=".''${prog}-wrapped"
What about `wrapProgram`?

2021-04-07 07:24 UTC, dasJ commented on packages/b3scale/default.nix
> +    owner = "infra.run/public";
There is a setting for this

2021-04-07 07:24 UTC, dasJ commented on modules/b3scale.nix
> +      type = lib.types.str;
`lib.types.float`

2021-04-07 07:24 UTC, dasJ commented on modules/b3scale.nix
> +      sandbox = 2;
```
stopIfChanged = false;
serviceConfig.Restart = "on-failure";
```

2021-04-07 07:24 UTC, dasJ commented on modules/b3scale.nix
> +    isMaster = (config.networking.hostName == cfg.master);
Vielleicht eher `cfg.master != null`?

2021-04-07 12:17 UTC, ajs124 commented on packages/b3scale/default.nix
> +      hidden=".''${prog}-wrapped"
iirc kann das arg0 nicht überschreiben.

2021-04-07 12:17 UTC, ajs124 commented on packages/b3scale/default.nix
> +    owner = "infra.run/public";
Für den owner? Was?

2021-04-07 12:18 UTC, ajs124 commented on modules/b3scale.nix
> +      type = lib.types.str;
I'd rather not. I don't trust floats.

2021-04-07 12:18 UTC, ajs124 commented on modules/b3scale.nix
> +      sandbox = 2;
`Restart = "on-failure"` ist doch schon gesetzt?

2021-04-07 12:19 UTC, ajs124 commented on modules/b3scale.nix
> +    isMaster = (config.networking.hostName == cfg.master);
Wieso? Ich will doch wissen, ob dieser host der master ist? master ist der hostname, der wird auch für die db connection benutzt.

2021-04-08 19:02 UTC, dasJ commented on packages/b3scale/default.nix
> +    owner = "infra.run/public";
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgitlab/default.nix#L11

2021-04-08 20:46 UTC, merged